name:  Teste CI-CD Cypress

on: 
    push: 
        branches: 
            - main
    workflow_dispatch:        

jobs: 
    Cypress-run:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout no código
              uses: actions/checkout@v3

            - name: Setup do Node
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            
            - name: Instalar dependencias 
              run: npm install

            - name: Executar testes
              run: npm test

            - name: Gerar relatório do Allure
              run: npm run report-ci

            - name: Publicar relatório do Allure
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: allure-results
              
        
    